### ISSUE TITLE
YoutubeDownload.py

### ISSUE THREAD

**Issue by Shuvo31** [Arka2001/Python-Projects#2]
Version: Python 3.9.5
IDE: Visual Studio Code

Error:
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\shuvo\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "c:\Users\shuvo\Desktop\Python Projects\youtube\youtube.py", line 28, in Downloader
    url =YouTube(str(link.get()))
  File "C:\Users\shuvo\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 73, in __init__
    self.video_id = extract.video_id(url)
  File "C:\Users\shuvo\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\extract.py", line 160, in video_id
    return regex_search(r"(?:v=|\/)([0-9A-Za-z_-]{11}).*", url, group=1)
  File "C:\Users\shuvo\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\helpers.py", line 129, in regex_search
    raise RegexMatchError(caller="regex_search", pattern=pattern)
pytube.exceptions.RegexMatchError: regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).*

**Comment by sayantandasgupta** [comment]
Have you installed pytube in your machine?

**Comment by Shuvo31** [comment]
yes!
